version: '3'
services:
      
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2


  customermanagementapi:
    image: pitstop/customermanagementapi:latest
    build: .
    depends_on:
      - sqlserver
    ports:
      - "5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  sqlserverdata:
    external: true    
  rabbitmqdata:
    external: true
